class MainLocators:
    BUTTON_ANIME = "//*[@class='nav-link']"
    BUTTON_MANGA = "//div[2]//ul[1]/li[2]/a"
    CHARACTERS = "Персонажи"
    CHARACTERS_XPATH = "//div[2]//ul[1]/li[3]/a"
    RANDOM_ANIME = 'Случайное аниме'
    SEARCH_STRING = "//div[2]//ul[2]/li[3]//input"
    BUTTON_SEARCH_STRING = "//*[@id='navbar-search']"
    GENRES = "//*[@id='filter']//div[2]/div[2]/button"
    CHOOSE_GENRES = "//*[@id='filter']/div[2]//span[7]/span"
    TYPE = "//*[@id='filter']//div[3]//button"
    CHOOSE_TYPE = "//*[@id='filter']//div[3]//label[1]/span"
    TYPE_OF_VOICE_ACTING = "//*[@id='filter']//div[4]//button"
    CHOOSE_VOICE_ACTING = "//*[@id='filter']//div[4]//label[1]/span"
    SEARCH_BUTTON = "//*[@id='filter']//div[8]/button"
    LINE_DATE = "//*[@id='slider-range']"
    TEXT_END_PAGE = "//*[@id='wrap']/div[7]//h2"
    ATTRIBUTE = '/html/head/link[2]'
    SCROLL_UP = "//*[@id='scrollUp']"
    ELEMENT_ONE = "//*[@id='wrap']/div[1]//li[1]/a"
    ELEMENT_TWO = "//*[@id='wrap']/div[1]//li[2]/a"
    ELEMENT_THREE = "//*[@id='wrap']/div[1]//li[3]/a"
    FOOTER_FIRST = "//*[@id='footer']//li[1]/a"
    FOOTER_SECOND = "//*[@id='footer']//li[2]/a"
    FOOTER_THIRD = "//*[@id='footer']//li[3]/a"
    SCHEDULE_ANIME = "//*[@id='wrap']/div[5]/div/div/div[2]//div[2]/div[1]/a"
    CHOOSE_ANIME_IN_SCHEDULE = "//*[@id='slide-toggle-thursday']/div[4]"
